
const CONFIG_KEYS = {
    // GOOGLE_AUTH_CLIENT_ID: process.env.REACT_APP_CLIENT_ID,
    // STRIPE_PUBLISHABLE_KEY: process.env.REACT_APP_STRIPE_PUBLISHABLE_KEY,
    // REDIRECT_URI: process.env.REACT_APP_REDIRECT_URI,
    API_BASE_URL: import.meta.env.VITE_API_BASE_URL,
  };
  export default CONFIG_KEYS;
  